name: Minedelivery
version: @version@
main: red.man10.minedelivery.Minedelivery

commands:
   mpost:
      description: This is a demo command.
      usage: /<command> [deli] [player]
      permission: tutorialplugin.mpost
      permission-message: You don't have <permission>